name: Run ScriptMy

on:
  schedule:
    - cron: '0 21 * * *'  # Запускать скрипт ежедневно в 21:00 UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server  # Установка MySQL
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 mysql-connector-python pytz lxml  # Установка необходимых библиотек

    - name: Start MySQL service
      run: |
        sudo service mysql start  # Запуск MySQL

    - name: Create MySQL database and user
      run: |
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS test_baza_mysql;"
        sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'AnosVoldigod0';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON test_baza_mysql.* TO 'root'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Run Python script
      run: python test_sql_parc_mysql.py  # Запуск скрипта парсинга
