name: Daily Python Combined Parser Baza Dana

on:
  schedule:
    - cron: '0 21 * * *'  # Запускать скрипт ежедневно в 00:00 UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  run-parsers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxi6 libgconf-2-4 xvfb  # Установка зависимостей для второго скрипта
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl lxml pytz datetime

    # Step 1: Запуск парсинга и обновления базы данных
    - name: Run Database Update Script
      run: python test_sql_parc.py  # Имя вашего скрипта, сохраняющего в базу данных

    # Step 2: Коммит и пуш обновлений базы данных
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add test_baza.db  # Поддержка базы данных
        git commit -m "Update test_baza.db with new data" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "No changes to push"

      # Step 2: Настройка виртуального дисплея для второго скрипта
    - name: Set up Xvfb for headless Chrome (for script 2)
      run: |
        Xvfb :99 -screen 0 1280x1024x16 &  # Запуск виртуального дисплея для headless Chrome
      env:
        DISPLAY: :99  # Указание переменной DISPLAY для всех последующих шагов

      # Step 3: Запуск второго скрипта
    - name: Run Python script 2
      run: python test_sql_parcV2.py  # Имя второго скрипта

    - name: Commit and push changes (script 2)
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add test_baza.db
        git commit -m "Update test_baza.db with new data" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "No changes to push"

      # Step 4: Запуск третьего скрипта
    - name: Run Python script 3
      run: python test_sql_parcV3.py  # Имя третьего скрипта

    - name: Commit and push changes (script 3)
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add test_baza.db
        git commit -m "Update test_baza.db with new data" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "No changes to push"