name: Run All Parsers Sequentially

on:
  schedule:
    - cron: '0 21 * * *'  # Запуск ежедневно в 21:00 UTC
  workflow_dispatch:  # Ручной запуск

jobs:
  run_parsers_sequentially:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Parser 1 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/parser1.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Parser 2 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/parser2.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Parser 3 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/parser3.yml/dispatches \
          -d '{"ref":"main"}'
