name: Run All Parsers Sequentially

on:
  schedule:
    - cron: '0 21 * * *'  # Запуск ежедневно в 21:00 UTC
  workflow_dispatch:  # Ручной запуск

jobs:
  trigger_parsers:
    runs-on: ubuntu-latest
    steps:
      # - name: Trigger Parser 1 Workflow
        # uses: peter-evans/workflow-dispatch@v1
        # with:
          # workflow: parser1.yml
          # ref: main  # Указываем ветку, с которой будем запускать
# 
      - name: Trigger Parser 2 Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: parser2.yml
          ref: main  # Указываем ветку, с которой будем запускать

      - name: Trigger Parser 3 Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: parser3.yml
          ref: main  # Указываем ветку, с которой будем запускать
