name: Run All Scripts Sequentially_mysql

on:
  schedule:
    - cron: '0 21 * * *'  # Schedule to run daily at 21:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_parsers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mysql-connector-python
          pip install selenium webdriver-manager beautifulsoup4 lxml pytz
      - name: Install MySQL Client
        run: sudo apt-get install mysql-client

      - name: Run Python parser 1
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_PORT: '3306'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'AnosVoldigod0'
          MYSQL_DATABASE: 'test_baza_mysql'
        run: |
          python test_sql_parc_mysql.py

      - name: Run Python parser 2
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_PORT: '3306'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'AnosVoldigod0'
          MYSQL_DATABASE: 'test_baza_mysql'
        run: |
          python test_sql_parc_mysqlV2.py

      - name: Run Python parser 3
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_PORT: '3306'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'AnosVoldigod0'
          MYSQL_DATABASE: 'test_baza_mysql'
        run: |
          python test_sql_parc_mysqlV3.py
