name: Run All Parsers Sequentially

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run_parsers_sequentially:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python parser 1
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/parser1.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Run Python parser 2
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/parser2.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Run Python parser 3
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/parser3.yml/dispatches \
          -d '{"ref":"main"}'
